apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexo-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hexo-blog
  template:
    metadata:
      labels:
        app: hexo-blog
    spec:
      containers:
      - name: hexo-blog
        image: gcr.io/mineonlium/blog
        ports:
        - containerPort: 4000
